<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "extbase_gallery"
 *
 * Auto generated by Extension Builder 2019-04-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'ExtbaseGallery',
    'description' => 'Simple Gallery Extension for TYPO3 based on Extbase/Fluid.',
    'category' => 'plugin',
    'author' => 'Christian Knell',
    'author_email' => 'christian.knell@balumedien.de',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
